# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jsdDistSafe <- function(p, q, addPseudocount) {
    .Call('_mirutil_jsdDistSafe', PACKAGE = 'mirutil', p, q, addPseudocount)
}

getDiNtFreq <- function(seqs, wts, reverse) {
    .Call('_mirutil_getDiNtFreq', PACKAGE = 'mirutil', seqs, wts, reverse)
}

